# Generated by Django 6.0.7 on 2026-07-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills e.g. Engine, Brakes, Electrical')),
                ('is_available', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='api.garage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Engine, Brakes, Electrical, Bodywork', max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.garage')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('owner', 'Garage Owner'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('receptionist', 'Receptionist')], default='mechanic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.garage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.CharField(blank=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=1, default=1.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicecatalog')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_used', to='api.workorder')),
            ],
        ),
    ]
